version: '3.1'

services:

  mariadb:
    image: mariadb
    restart: always
    container_name: my-maria
#    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=<PASSWORD>
      #      - MYSQL_DATABASE=test
      - MYSQL_USER=api-server
      - MYSQL_PASSWORD=<PASSWORD>

  postgres:
    image: postgres:14
    restart: always
    container_name: my-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: <PASSWORD>

  redis:
    image: redis
    restart: always
    hostname: my-redis
    container_name: my-redis
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
      - /tmp/redis:/tmp/redis
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf

